<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UltraPrint.Core/UltraPrint.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.OleDb" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Layout/Templates/UltraPrint22115Template.ly" />
  </ItemGroup>
</Project>