<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UltraPrint.Core/UltraPrint.Core.csproj" />
    <ProjectReference Include="../UltraPrint.Legacy/UltraPrint.Legacy.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../samples/legacy/Campo.ini" Link="Campo.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
